create database Attendance;
create table Defaulters(id varchar(30),name varchar(30));
select * from Defaulters;
create table Adata(id varchar(30),name varchar(30),rollno int);
alter table Adata add date varchar(30);
alter table Defaulters add rollno int;
select * from Adata;
alter table Adata alter column rollno varchar(30);
select * from Student;
create table Student(id varchar(30),name varchar(30),rollno varchar(30),class varchar(30));
insert into Student values('C1 F3 55 46','Sanjana','3','TY Bsc');
select * from Student where name not in(select name from Adata);
delete from Adata where name='Sachin';
alter table Adata add time varchar(20);
delete from Adata where name='Sanj';
create table Monthly(name varchar(30),present varchar(30),absent varchar(30));
insert into Monthly(present) values(select COUNT(date) from Adata where date='10-01-2019');
select * from Monthly;
select COUNT(date) from Adata where name='Sanjana';
select COUNT(name) from Adata where date='10-01-2019';
select COUNT(date) from Adata;
select * from Adata;

select  name,date from Adata  where Adata.date>='1-01-2019' AND Adata.date<='31-01-2019'  ;
select name,COUNT(date) from Adata GROUP BY name ;
select name,COUNT(date) AS Present from Adata GROUP BY name ;
select COUNT(name) AS  Absent from Adata  where name  not in Adata And ;
select name,COUNT(date) from Adata where Adata.date>='1-01-2019' AND Adata.date<='31-01-2019';
select name,COUNT(date) as Present from Adata group by date Having Present<='10-01-2019';
alter table Adata add  month varchar(20);
insert into Adata(id,name,rollno,date,time) values('C1 F3 55 46','Sanjana','3','02-02-2019','02:11');
update Adata set month='2' where date='02-02-2019';
select count(date) from Adata where name='Sanjana' and month='1';
select name,count(date) from Adata where month='1' group by name;
delete from Sachin where date='08:52';
insert into Adata(id,name,rollno,date,time,month) values('C1 F3 55 46','Sanjana','3','15-01-2019','02:11','1');
create table Yashchar(id varchar(20),lectime varchar(20),lec varchar(20),time varchar(20),date varchar(20),month varchar());
select * from Sachin;
create table Sachin(id varchar(20),lectime varchar(20),lec varchar(20),time varchar(20),date varchar(20),month varchar(20));
create table Sanjana(id varchar(20),lectime varchar(20),lec varchar(20),time varchar(20),date varchar(20),month varchar(20));
create table Late(id varchar(20),Name varchar(20),lectime varchar(20),lec varchar(20),time varchar(20),date varchar(20),month varchar(20));
select * from Student;
select * from Late;
select * from Yash where date not in(select name from Adata where date='"+today+"')
select * from Student where id in(select id from Sachin where date='06-02-2019');
create table Att(id varchar(20),name varchar(20),lectime varchar(20),lec varchar(20),time varchar(20),date varchar(20),month varchar(20));
create table MasterAttend(id varchar(20),lectime varchar(20),lec varchar(20),name varchar(20),time varchar(20),date varchar(20),month varchar(20));
select *from MasterAttend;
select * from Student where name not in(select name from MasterAttend where date='11-02-2019');
select lectime,lec,name,count(date) as Present from MasterAttend where month='11 February' group by lec;
select lectime,lec,name from MasterAttend where month='11 February';
select lectime,lec,name,count(date) as Present from MasterAttend where month='February' group by name,lec,lectime;
create table Defaulter(id varchar(30),name varchar(30),rollno varchar(30),class varchar(30),percentage float);
select * from Defaulter;
insert into Defaulter(id,name,rollno,class) values('C1 F3 55 46','Sanjana','3','TY Bsc');
select Student.id, Student.name, Student.rollno, Student.class,Defaulter.percentage from Student,Defaulter where Student.id = Defaulter.id;
insert into MasterAttend values('91 3C 23 2F','7:30-9:10','SQA','Yash','07:35','11-02-2019','February');
insert into MasterAttend values('C1 F3 55 46','7:30-9:10','SQA','Sanjana','07:37','11-02-2019','February');
insert into Defaulter(percentage) values(22.00) where name='Yash';
update Defaulter set percentage=0 where name='Sanjana';
select name,count(date) from MasterAttend group by name;
create table Lecture(lectime varchar(20),lec varchar(20),id varchar(20));
insert into Lecture(lectime,lec,id) values('7:30-9:10','SQA','C1 F3 55 46'); 
insert into Lecture(lectime,lec,id) values('9:30-11:10','BI','91 3C 23 2F'); 
insert into Lecture(lectime,lec,id) values('11:11-12:50','EN','35 66 2E 83'); 
select * from MasterAttend;
insert into Lecture(lectime,lec) values('11:11-12:50','EN'); 
insert into Lecture(lectime,lec) values('9:30-11:10','BI');
alter table Lecture add  id varchar(20);
update Lecture set id='35 66 2E 83' where lec='BI';
select lectime,lec,name,count(date) as Present from MasterAttend where month='February' group by lectime,lec,name;
delete from MasterAttend where time='06:49';
select name,count(date) from MasterAttend group by name;
select Student.id, Student.name, Student.rollno, Student.class,Defaulter.percentage from Student,Defaulter where Student.id = Defaulter.id AND Student.name='Sachin';
select * from Student where name not in(select name from MasterAttend where date='14-02-2019');
select * from Student;
alter table Student add phno varchar(30);
update Student set phno='7718049022' where rollno='3';